### 

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtdWx0aXBsYXllci1nYW1lLXNlcnZlciIsInN1YiI6IjEiLCJleHAiOjE3NTg5ODI5ODIsImlhdCI6MTc1ODk4MjY4Mn0.ovrJgUxJt-rpxsmUu0jJN3Q2sqcs7R94h4sLarXrRFA
@hostname = http://localhost:8080


### 

POST {{hostname}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@localhost.com",
  "first_name": "Daniel",
  "last_name": "Wiratman",
  "password": "test1234"
}


### 

POST {{hostname}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@localhost.com",
  "password": "test1234"
}


### 

GET {{hostname}}/player/me HTTP/1.1
Authorization: Bearer {{access_token}}
