FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server .


FROM alpine:3

RUN adduser -D -g '' appuser

WORKDIR /home/appuser

COPY --from=builder /app/server .

USER appuser

EXPOSE 8080

CMD ["./server"]
